[phases.setup]
apt = ["python3", "python3-pip", "python3-venv"]

[phases.install]
commands = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.start]
commands = ["python3 bot.py"]
